version: '3'

services:
    db:
        image: mysql:5.7
        container_name: mysql-container
        volumes:
          - mysql_data:/var/lib/postgresql/data/
        environment:
          MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
          MYSQL_DATABASE: $MYSQL_DATABASE
          MYSQL_USER: $MYSQL_USER
          MYSQL_PASSWORD: $MYSQL_PASSWORD
    app:
        build: .
        ports:
          - "${PORTS}:9999"
        container_name: golang-restapi
        restart: on-failure:10
        depends_on:
          - db
volumes:
  mysql_data: